#!/usr/bin/env bash
# infra/scripts/init.sh
# Full bootstrap for the smatch Azure local development environment.
# Run once from the repo root: bash infra/scripts/init.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
INFRA_DIR="$REPO_ROOT/infra/terraform"
SCRIPT_DIR="$REPO_ROOT/infra/scripts"

log() { echo "[init] $*"; }

# ── 1. Load .env file ────────────────────────────────────────────────────────
ENV_FILE="${REPO_ROOT}/.env"
if [[ -f "$ENV_FILE" ]]; then
  log "Loading $ENV_FILE..."
  set -o allexport
  source <(grep -E '^[[:space:]]*[a-zA-Z_][a-zA-Z0-9_]*=' "$ENV_FILE")
  set +o allexport
else
  log "WARNING: .env not found at $ENV_FILE — relying on exported shell variables."
fi

# ── 2. Check required tools ──────────────────────────────────────────────────
for cmd in docker psql az; do
  if ! command -v "$cmd" &>/dev/null; then
    echo "ERROR: '$cmd' is not installed or not on PATH."
    exit 1
  fi
done

# ── 3. Verify Azure login ────────────────────────────────────────────────────
log "Verifying Azure CLI login..."
az account show &>/dev/null || {
  log "Not logged in. Running 'az login'..."
  az login
}

# ── 4. Start local infrastructure (Docker Compose) ───────────────────────────
log "Starting local infrastructure (Postgres, Redis, Azurite)..."
cd "$REPO_ROOT"
docker compose up -d postgres redis azurite

log "Waiting for services to be healthy..."
for i in $(seq 1 30); do
  PG_OK=$(docker compose exec -T postgres pg_isready -U postgres -d smatch 2>/dev/null || true)
  if [[ "$PG_OK" == *"accepting connections"* ]]; then
    log "Postgres is ready."
    break
  fi
  if [[ $i -eq 30 ]]; then
    echo "ERROR: Postgres did not become ready in time."
    docker compose logs postgres
    exit 1
  fi
  sleep 2
done

# ── 5. Run database migrations ────────────────────────────────────────────────
log "Running database migrations..."
DATABASE_URL="${DATABASE_URL:-postgresql://postgres:postgres@localhost:5432/smatch?sslmode=disable}" \
  bash "$SCRIPT_DIR/migrate.sh"

# ── 6. Start pg_tileserv ──────────────────────────────────────────────────────
log "Starting pg_tileserv..."
docker compose up -d pg_tileserv

# ── 7. Write .env.azurite with resolved values ────────────────────────────────
ENVFILE="$REPO_ROOT/.env.azurite"
cat > "$ENVFILE" <<ENVEOF
# Auto-generated by infra/scripts/init.sh — do not edit manually.
# Use this to run the backend locally against local Docker services + Azurite.

PORT=3000
NODE_ENV=development

DATABASE_URL=postgresql://postgres:postgres@localhost:5432/smatch?sslmode=disable

REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_PASSWORD=
REDIS_TLS_ENABLED=false

FIREBASE_CREDENTIALS_FILE=smatch-badminton-firebase-adminsdk-fbsvc-fb65abab30.json

AZURE_STORAGE_ACCOUNT=devstoreaccount1
AZURE_STORAGE_KEY=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
AZURE_BLOB_ENDPOINT=http://localhost:10000/devstoreaccount1
AZURE_STORAGE_CONTAINER_PROFILE=smatch-profiles
AZURE_STORAGE_CONTAINER_MATCHES=smatch-matches
AZURE_STORAGE_CONTAINER_BUSINESS_DOCS=smatch-business-docs

TILE_SERVER_URL=http://localhost:7800

ZALOPAY_APP_ID=${ZALOPAY_APP_ID:-}
ZALOPAY_KEY1=${ZALOPAY_KEY1:-}
ZALOPAY_KEY2=${ZALOPAY_KEY2:-}
ZALOPAY_ENDPOINT=${ZALOPAY_ENDPOINT:-https://sb-openapi.zalopay.vn}
ZALOPAY_CALLBACK_URL=${ZALOPAY_CALLBACK_URL:-}

SLOT_LOCK_TTL_SECONDS=600
ADMIN_SECRET=${ADMIN_SECRET:-}
ENVEOF
log ".env.azurite written."

# ── 8. Terraform init (for cloud deployment, not local) ───────────────────────
log ""
log "For cloud deployment, run:"
log "  cd $INFRA_DIR"
log "  terraform init"
log "  terraform plan -out tfplan.out"
log "  terraform apply tfplan.out"
log ""
log "=== Bootstrap complete ==="
log ""
log "Azurite (Blob):  http://localhost:10000"
log "To run the backend locally:"
log "  cp .env.azurite .env && go run ./cmd/server"
