export const SURFACE_TYPES = ['synthetic', 'wood', 'concrete', 'rubber', 'other'] as const

export const BANK_LIST = [
  'Agribank',
  'Vietcombank',
  'BIDV',
  'VietinBank',
  'OceanBank',
  'GPBank',
  'CBBank',
  'ABBANK',
  'ACB',
  'Bac A Bank',
  'BaoViet Bank',
  'BVBank',
  'DongA Bank',
  'Eximbank',
  'HDBank',
  'Kienlongbank',
  'LPBank',
  'MBBank',
  'MSB',
  'Nam A Bank',
  'NCB',
  'OCB',
  'PGBank',
  'PVcomBank',
  'Sacombank',
  'Saigonbank',
  'SCB',
  'SeABank',
  'SHB',
  'Techcombank',
  'TPBank',
  'VIB',
  'Viet A Bank',
  'VietBank',
  'VPBank',
  'CIMB',
  'Hong Leong Bank',
  'HSBC',
  'Public Bank',
  'Shinhan Bank',
  'Standard Chartered',
  'UOB',
  'Woori Bank',
  'Indovina Bank',
  'VRB',
  'VBSP',
  'VDB',
  "Co-opBank",
]
